#!/bin/bash
# Sync OpenClaw memories to Obsidian Memory vault
# Usage: ./scripts/sync-memories-to-obsidian.sh
# 
# NOTE: If your Obsidian vault is on a different machine (e.g., your Mac),
# you need to either:
# 1. Run this script on that machine (with access to the workspace)
# 2. Use SSH/SCP to push files from VPS to your Mac
# 3. Use a sync tool like Syncthing, Dropbox, etc.
#
# For Mac users with Obsidian at /Users/mat/Documents/obsidian-memory:
# Set OBSIDIAN_MEMORY_DIR environment variable or edit below.

set -e

# Source: OpenClaw workspace memories
SOURCE_DIR="${SOURCE_DIR:-/root/.openclaw/workspace/memory}"

# Destination: Obsidian Memory vault
# Default: local path (for running on same machine)
# For Mac: /Users/mat/Documents/obsidian-memory
# For iCloud: $HOME/Library/Mobile Documents/com~apple~CloudDocs/Documents/Obsidian Memory
DEST_DIR="${OBSIDIAN_MEMORY_DIR:-$HOME/Library/Mobile Documents/com~apple~CloudDocs/Documents/Obsidian Memory}"

# Check if we're running on the VPS but need to sync to a Mac
# Set these environment variables for remote sync:
#   OBSIDIAN_SSH_HOST=your-mac-hostname-or-ip
#   OBSIDIAN_SSH_USER=mat
#   OBSIDIAN_MEMORY_DIR=/Users/mat/Documents/obsidian-memory
if [ -n "$OBSIDIAN_SSH_HOST" ] && [ -n "$OBSIDIAN_SSH_USER" ]; then
    echo "🧠 Syncing memories to Obsidian (remote: $OBSIDIAN_SSH_HOST)..."
    echo "Source: $SOURCE_DIR"
    echo "Destination: $OBSIDIAN_SSH_USER@$OBSIDIAN_SSH_HOST:$DEST_DIR"
    echo ""
    
    # Sync via SSH/SCP
    if [ -d "$SOURCE_DIR" ]; then
        # Ensure destination exists on remote
        ssh "$OBSIDIAN_SSH_USER@$OBSIDIAN_SSH_HOST" "mkdir -p '$DEST_DIR'"
        
        # Sync files via rsync or scp
        if command -v rsync &> /dev/null; then
            rsync -avz --delete "$SOURCE_DIR/" "$OBSIDIAN_SSH_USER@$OBSIDIAN_SSH_HOST:$DEST_DIR/"
        else
            # Fallback to scp
            scp -r "$SOURCE_DIR"/* "$OBSIDIAN_SSH_USER@$OBSIDIAN_SSH_HOST:$DEST_DIR/" 2>/dev/null || true
        fi
        
        echo "✅ Remote sync complete!"
    else
        echo "  ⚠️ Source directory not found: $SOURCE_DIR"
        exit 1
    fi
    exit 0
fi

# Local sync (same machine)
echo "🧠 Syncing memories to Obsidian..."
echo "Source: $SOURCE_DIR"
echo "Destination: $DEST_DIR"
echo ""

# Create destination if it doesn't exist
mkdir -p "$DEST_DIR"

# Timestamp for this sync
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

# Sync all .md files from memory directory
if [ -d "$SOURCE_DIR" ]; then
    # Copy daily memory files
    find "$SOURCE_DIR" -maxdepth 1 -name "*.md" -type f | while read -r file; do
        filename=$(basename "$file")
        cp "$file" "$DEST_DIR/$filename"
        echo "  ✓ $filename"
    done
    
    # Copy subdirectories (guides, projects, data, etc.)
    for subdir in guides projects data; do
        if [ -d "$SOURCE_DIR/$subdir" ]; then
            mkdir -p "$DEST_DIR/$subdir"
            find "$SOURCE_DIR/$subdir" -name "*.md" -type f | while read -r file; do
                rel_path="${file#$SOURCE_DIR/}"
                dest_file="$DEST_DIR/$rel_path"
                mkdir -p "$(dirname "$dest_file")"
                cp "$file" "$dest_file"
                echo "  ✓ $rel_path"
            done
        fi
    done
else
    echo "  ⚠️ Source directory not found: $SOURCE_DIR"
    exit 1
fi

# Create/update a sync log
cat > "$DEST_DIR/.last-sync.md" << EOF
---
synced_at: $TIMESTAMP
source: OpenClaw Workspace
files_synced: $(find "$DEST_DIR" -name "*.md" -type f | wc -l)
---

# Memory Sync Log

Last synced: $TIMESTAMP

## Files in Obsidian Memory
$(find "$DEST_DIR" -name "*.md" -type f ! -name ".last-sync.md" | sed 's|.*/||' | sort | sed 's/^/- /')

---
*Auto-generated by OpenClaw memory sync*
EOF

echo ""
echo "✅ Sync complete!"
echo "📁 Files synced to: $DEST_DIR"
echo "📊 Total markdown files: $(find "$DEST_DIR" -name "*.md" -type f | wc -l)"
